# Generated by Django 2.0 on 2018-01-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.CharField(max_length=10, unique=True)),
                ('type', models.SmallIntegerField()),
                ('co_name', models.CharField(max_length=100, null=True)),
                ('co_addr', models.CharField(max_length=100, null=True)),
                ('co_tel', models.CharField(max_length=20, null=True)),
                ('tax_id', models.CharField(max_length=100, null=True)),
                ('account_owner', models.CharField(max_length=50, null=True)),
                ('account_number', models.CharField(max_length=20, null=True)),
                ('account_bank', models.CharField(max_length=100, null=True)),
                ('contact_name', models.CharField(max_length=100, null=True)),
                ('contact_tel', models.CharField(max_length=20, null=True)),
                ('contact_role', models.CharField(max_length=100, null=True)),
                ('contract_start', models.CharField(max_length=20, null=True)),
                ('contract_end', models.CharField(max_length=20, null=True)),
                ('contract_file', models.CharField(max_length=100, null=True)),
            ],
            options={
                'permissions': (('view_client', 'Can access information of client'), ('change_client_contract', 'Can edit contract of client'), ('change_client_tax', 'Can edit tax_id of client')),
            },
        ),
        migrations.CreateModel(
            name='SUPPLIER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.CharField(max_length=10, unique=True)),
                ('type', models.SmallIntegerField()),
                ('co_name', models.CharField(max_length=100, null=True)),
                ('co_addr', models.CharField(max_length=100, null=True)),
                ('co_tel', models.CharField(max_length=20, null=True)),
                ('tax_id', models.CharField(max_length=100, null=True)),
                ('account_owner', models.CharField(max_length=50, null=True)),
                ('account_number', models.CharField(max_length=20, null=True)),
                ('account_bank', models.CharField(max_length=100, null=True)),
                ('contact_name', models.CharField(max_length=100, null=True)),
                ('contact_tel', models.CharField(max_length=20, null=True)),
                ('contact_role', models.CharField(max_length=100, null=True)),
                ('contract_start', models.CharField(max_length=20, null=True)),
                ('contract_end', models.CharField(max_length=20, null=True)),
                ('contract_file', models.CharField(max_length=100, null=True)),
            ],
            options={
                'permissions': (('view_supplier', 'Can access information of supplier'), ('change_supplier_contract', 'Can edit contract of supplier'), ('change_supplier_tax', 'Can edit tax_id of supplier')),
            },
        ),
    ]
