# Generated by Django 2.0 on 2018-01-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_order_order_sup_allo_sup_op'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ORDER',
        ),
    ]
