# Generated by Django 2.0 on 2018-01-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ORDER',
        ),
    ]
