# Generated by Django 2.0 on 2018-01-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='clear_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
    ]
