# Generated by Django 2.0 on 2018-01-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_auto_20180131_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='create_time',
        ),
    ]
