# Generated by Django 2.0 on 2018-01-31 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0011_order_create_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ORDER',
        ),
    ]
