# Generated by Django 2.0 on 2018-01-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0012_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.CharField(max_length=12, unique=True)),
                ('status', models.SmallIntegerField()),
                ('client_id', models.IntegerField()),
                ('dep_place', models.CharField(max_length=200)),
                ('dep_city', models.CharField(max_length=50)),
                ('des_place', models.CharField(max_length=200)),
                ('des_city', models.CharField(max_length=50)),
                ('cargo_name', models.CharField(max_length=100)),
                ('cargo_weight', models.FloatField(max_length=100)),
                ('cargo_quantity', models.IntegerField()),
                ('note', models.CharField(max_length=500, null=True)),
                ('receiveables', models.FloatField(null=True)),
                ('received', models.FloatField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('clear_time', models.DateTimeField(null=True)),
                ('if_delete', models.SmallIntegerField()),
            ],
            options={
                'permissions': (('view_order', 'Can access information of orders'), ('view_trash_order', 'Can access information of trash box')),
            },
        ),
    ]
