# Generated by Django 2.0 on 2018-01-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0013_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ORDER_SUP_ALLO',
        ),
    ]
