# Generated by Django 2.0 on 2018-01-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0014_delete_order_sup_allo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORDER_SUP_ALLO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField()),
                ('order_id', models.IntegerField()),
                ('operation', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('payables', models.FloatField(null=True)),
                ('paid_cash', models.FloatField(null=True)),
                ('paid_oil', models.FloatField(null=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('clear_time', models.DateField(null=True)),
            ],
        ),
    ]
