# Generated by Django 2.0 on 2018-02-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0016_auto_20180131_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rec_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='rec_tel',
            field=models.CharField(default='', max_length=50),
        ),
    ]
