# Generated by Django 2.0 on 2018-02-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0017_auto_20180205_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOG_TRACE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
