# Generated by Django 2.0 on 2018-02-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0018_log_trace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LOG_TRACE',
        ),
    ]
