# Generated by Django 2.0 on 2018-02-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0019_delete_log_trace'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOG_TRACE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('desc', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
