# Generated by Django 2.0 on 2018-02-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0020_log_trace'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAYABLES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField()),
                ('order_id', models.IntegerField()),
                ('operation', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('supplier_id', models.IntegerField()),
                ('payables', models.FloatField(null=True)),
                ('paid_cash', models.FloatField(null=True)),
                ('paid_oil', models.FloatField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('clear_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RECEIVEABLES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField()),
                ('order_id', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('client_id', models.IntegerField()),
                ('receiveables', models.FloatField(null=True)),
                ('received', models.FloatField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('clear_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ORDER_SUP_ALLO',
        ),
    ]
