# Generated by Django 2.0 on 2018-02-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0021_auto_20180209_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payables',
            old_name='operation',
            new_name='step',
        ),
        migrations.RemoveField(
            model_name='receiveables',
            name='client_id',
        ),
    ]
