# Generated by Django 2.0 on 2018-02-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0022_auto_20180211_0426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SUP_OP',
            new_name='SUP_STEP',
        ),
    ]
