# Generated by Django 2.0 on 2018-02-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0025_auto_20180212_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='payables',
            name='invoice',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receiveables',
            name='invoice',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
