# Generated by Django 2.0 on 2018-02-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0026_auto_20180226_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='remark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payables',
            name='remark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='receiveables',
            name='remark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='remark',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
