# Generated by Django 2.0 on 2018-02-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0027_auto_20180227_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='note',
            new_name='remark',
        ),
    ]
