# Generated by Django 2.0 on 2018-02-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0028_auto_20180228_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_size',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_weight',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dep_place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='des_place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
