# Generated by Django 2.0 on 2018-02-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0029_auto_20180228_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payables',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
