# Generated by Django 2.0 on 2018-02-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0030_auto_20180228_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo_quantity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
