# Generated by Django 2.0 on 2018-03-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0032_recv_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RECV_INVOICE',
        ),
    ]
