# Generated by Django 2.0 on 2018-03-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0033_delete_recv_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RECV_INVOICE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=100)),
                ('client_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(max_length=100, null=True)),
                ('create_user', models.CharField(max_length=100)),
            ],
        ),
    ]
