# Generated by Django 2.0 on 2018-03-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0034_recv_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveables',
            name='invoice',
            field=models.IntegerField(null=True),
        ),
    ]
